export const englishTexts = {
  navHome: "home",
  navAbout: "about",
  navProjects: "projects",
  navContact: "contact",
  navBlog: "blog",
  heroDescription: "Hi there! I'm Cristina — a curious web developer always learning, building, and having fun with code.",
  flipCoffee: "coffee into code ☕",
  flipIdeas: "ideas into apps 💡",
  flipBugs: "bugs into features 🐞",
  flipChaos: "chaos into components 🧩",
  flipLines: "lines into logic 📝",
  flipDreams: "dreams into deploys 🚀",
  flipPrefix: "I turn",
  aboutTitle: "About Me",
  projectsTitle: "My Projects",
  contactTitle: "Let's Chat!",
  testText: "This is a test text in English",
  projectsButton: "My projects",
  aboutDescription: "Probably one of the few developers who started with MS-DOS at 14, took a detour into tourism, and eventually found my way back to coding, because my heart never really left. <br><br>I believe in following your passions, even if they take you on the scenic route first.",
  myVibeTitle: "My Vibe",
  vibeMusic: "Coding soundtrack: Phoenix, The Strokes, The Smiths & reggae — because good code deserves good music.",
  vibeSurf: "Surf & code balance — when I'm stuck on a bug, the ocean usually has the solution.",
  vibeCSS: "CSS enthusiast — I'll happily refactor styling three times if it makes things look better.",
  vibeProblem: "Stubborn problem-solver — I don't give up easily, but I'm smart enough to take breaks and come back stronger.",
  vibeExplore: "Code and explore — I believe the best inspiration comes from new places and unfamiliar horizons.",
  myJourneyTitle: "My Journey",
  journeyDescription: "Whether it was upgrading hardware as a teen or helping travelers navigate new places, I've always loved solving puzzles and making connections. Now I bring that same curiosity to coding — creating digital experiences that work smoothly and feel right to real people.",
  quote: "The best code comes from people who understand both computers AND humans.",
  technologiesTitle: "Technologies I use",

  // Horse Race Game
  horseRaceTitle: "Horse Race Game",
  horseRaceDescription: "A fun horse racing game where players place bets and watch the action unfold in real-time. I built this to learn how desktop applications work with databases - every race result gets saved to MySQL.",
  horseRaceChallenge: "The biggest challenge was making the JavaFX interface feel lively and keeping the game data in sync. It was my first deep dive into real-time updates.",
  horseRaceTech: "Built with: Java, JavaFX, MySQL.",
  viewCode: "🔗 View Code",
  liveDemo: "🌐 Live Demo",

  // Coffee App
  coffeeAppTitle: "Coffee App",
  coffeeAppDescription: "My first proper Angular app! It connects to a coffee API and shows different brew styles in a clean, responsive layout. Perfect for coffee lovers who enjoy exploring new brews.",
  coffeeAppChallenge: "This project really helped me understand how components talk to each other and how to handle data from external APIs. I learned to love TypeScript's type safety along the way.",
  coffeeAppTech: "Built with: Angular, TypeScript, HTML, CSS.",

  // Breakout Game
  breakoutTitle: "Breakout Game",
  breakoutDescription: "A Python recreation of the classic Breakout game from a Stanford course. It was my first time doing anything with graphics programming - watching those bricks break never gets old!",
  breakoutChallenge: "Getting collision detection right was tricky, but so satisfying once it worked. This project showed me how games manage state and handle user input in real-time.",
  breakoutTech: "Built with: Python, graphics.py.",

  contactDescription: "Got an idea for a project or just want to talk tech?<br>I'd love to hear from you - drop me a message below or connect on LinkedIn.",
  emailButton: "✉️ Email Me",
  linkedinButton: "🔗 LinkedIn",
  sendButton: "Send Message",
  emailLabel: "Your email",
  emailPlaceholder: "your.email@example.com",
  messageLabel: "What's on your mind?",
  messagePlaceholder: "Hey Cristina, I'd love to talk about...",
  footerText: "Made with ❤️ by Cristina — Personal portfolio",
  github: "GitHub",
  linkedin: "LinkedIn",
  cv: "CV",
  blog: "Blog",
  privacyPolicy: "Privacy Policy"
};

export const spanishTexts = {
  navHome: "inicio",
  navAbout: "sobre mí",
  navProjects: "proyectos",
  navContact: "contacto",
  navBlog: "blog",
  heroDescription: "¡Hola! Soy Cristina – una desarrolladora web curiosa que siempre está aprendiendo, construyendo y divirtiéndose con el código.",
  flipCoffee: "café en código ☕",
  flipIdeas: "ideas en apps 💡",
  flipBugs: "bugs en features 🐞",
  flipChaos: "caos en componentes 🧩",
  flipLines: "líneas en lógica 📝",
  flipDreams: "sueños en deploys 🚀",
  flipPrefix: "Convierto",
  aboutTitle: "Sobre Mí",
  projectsTitle: "Proyectos",
  contactTitle: "¡Hablemos!",
  testText: "Este es un texto de prueba en español",
  projectsButton: "Mis proyectos",
  aboutDescription: "Probablemente una de las pocas desarrolladoras que empezó con MS-DOS a los 14 años, tomó un desvío hacia el turismo y finalmente encontró su camino de vuelta a la programación, porque mi corazón nunca se fue realmente. <br><br>Creo en seguir tus pasiones, incluso si te llevan primero por la ruta escénica.",
  myVibeTitle: "Mi Estilo",
  vibeMusic: "Banda sonora para programar: Phoenix, The Strokes, The Smiths & reggae — porque el buen código merece buena música.",
  vibeSurf: "Equilibrio entre surf y código — cuando me atasco con un bug, el océano suele tener la solución.",
  vibeCSS: "Entusiasta del CSS — refactorizaré el estilo tres veces con gusto si hace que las cosas se vean mejor.",
  vibeProblem: "Solucionadora de problemas obstinada — no me rindo fácilmente, pero soy lo suficientemente inteligente para tomar descansos y volver más fuerte.",
  vibeExplore: "Codificar y explorar — creo que la mejor inspiración viene de lugares nuevos y horizontes desconocidos.",
  myJourneyTitle: "Mi Trayectoria",
  journeyDescription: "Ya fuera actualizando hardware de adolescente o ayudando a viajeros a navegar por nuevos lugares, siempre me ha encantado resolver puzzles y hacer conexiones. Ahora llevo esa misma curiosidad a la programación — creando experiencias digitales que funcionan sin problemas y se sienten bien para las personas reales.",
  quote: "El mejor código viene de personas que entienden tanto a los ordenadores COMO a los humanos.",
  technologiesTitle: "Tecnologías que uso",

  // Horse Race Game
  horseRaceTitle: "Juego de Carreras de Caballos",
  horseRaceDescription: "Un divertido juego de carreras de caballos donde los jugadores apuestan y ven la acción desarrollarse en tiempo real. Lo construí para aprender cómo funcionan las aplicaciones de escritorio con bases de datos - cada resultado de carrera se guarda en MySQL.",
  horseRaceChallenge: "El mayor desafío fue hacer que la interfaz de JavaFX se sintiera viva y mantener los datos del juego sincronizados. Fue mi primera inmersión profunda en actualizaciones en tiempo real.",
  horseRaceTech: "Construido con: Java, JavaFX, MySQL.",
  viewCode: "🔗 Ver Código",
  liveDemo: "🌐 Demo en Vivo",

  // Coffee App
  coffeeAppTitle: "Coffee App",
  coffeeAppDescription: "¡Mi primera aplicación Angular pro! Se conecta a una API de café y muestra diferentes estilos de preparación en un diseño limpio y responsive. Perfecto para los amantes del café que disfrutan explorando nuevas preparaciones.",
  coffeeAppChallenge: "Este proyecto realmente me ayudó a entender cómo se comunican los componentes entre sí y cómo manejar datos de APIs externas. Aprendí a amar la seguridad de tipos de TypeScript en el proceso.",
  coffeeAppTech: "Construido con: Angular, TypeScript, HTML, CSS.",

  // Breakout Game
  breakoutTitle: "Juego Breakout",
  breakoutDescription: "Una recreación en Python del clásico juego Breakout de un curso de Stanford. Fue mi primera vez haciendo algo con programación gráfica - ¡ver esos ladrillos romperse nunca pasa de moda!",
  breakoutChallenge: "Conseguir que la detección de colisiones funcionara correctamente fue complicado, pero muy satisfactorio una vez que funcionó. Este proyecto me mostró cómo los juegos gestionan el estado y manejan la entrada del usuario en tiempo real.",
  breakoutTech: "Construido con: Python, graphics.py.",

  contactDescription: "¿Tienes una idea para un proyecto o simplemente quieres hablar de tecnología?<br>Me encantaría saber de ti - envíame un mensaje o conéctemos en LinkedIn.",
  emailButton: "✉️ Enviar Email",
  linkedinButton: "🔗 LinkedIn",
  sendButton: "Enviar Mensaje",
  emailLabel: "Tu email",
  emailPlaceholder: "tu.email@ejemplo.com",
  messageLabel: "¿Qué tienes en mente?",
  messagePlaceholder: "Hola Cristina, me encantaría hablar sobre...",
  footerText: "Hecho con ❤️ por Cristina — Portfolio personal",
  github: "GitHub",
  linkedin: "LinkedIn",
  cv: "CV",
  blog: "Blog",
  privacyPolicy: "Política de Privacidad"
};